package utils;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class Hashing {
  
  public static byte[] sha256StringHash(String input) throws NoSuchAlgorithmException {
    MessageDigest md = MessageDigest.getInstance("SHA-256");
    return md.digest(input.getBytes(StandardCharsets.UTF_8));
  }

  public static byte[] sha256BytesHash(byte[] input) throws NoSuchAlgorithmException {
    MessageDigest md = MessageDigest.getInstance("SHA-256");
    return md.digest(input);
  }

  public static String toHexString(byte[] hash) {
    StringBuilder hex = new StringBuilder(hash.length * 2);
    for (byte b : hash) {
        hex.append(String.format("%02x", b));
    }
    return hex.toString();
}


  public static void main(String args[])
    {
        try
        {
            System.out.println("HashCode Generated by SHA-256 for:");

            String s1 = "GeeksForGeeks";
            System.out.println("\n" + s1 + " : " + sha256StringHash(s1));
            System.out.println("\n" + s1 + " : " + toHexString(sha256StringHash(s1)));

            String s2 = "hello world";
            System.out.println("\n" + s2 + " : " + sha256StringHash(s2));
            System.out.println("\n" + s2 + " : " + toHexString(sha256StringHash(s2)));
            
            String s3 = "K1t4fo0V"; 
            System.out.println("\n" + s3 + " : " + sha256StringHash(s3));
            System.out.println("\n" + s3 + " : " + toHexString(sha256StringHash(s3)));
        }
        // For specifying wrong message digest algorithms
        catch (NoSuchAlgorithmException e) {
            System.out.println("Exception thrown for incorrect algorithm: " + e);
        }
    }
}